# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/gunnar/setup-makefiles.sh
#
# I'm a lasagna hog, go hang a salami
#

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),gunnar)

endif
